### ISSUE TITLE
Change Request #10 Database improvement by adding user unique ID to every product entry

### ISSUE THREAD

**Issue by saniluqman** [saniluqman/G1_Picasso_Inventory_System#10]
This request is to help tracking user activities. Need to improve database for data accuracy.

![image](https://user-images.githubusercontent.com/6891612/169692045-63e4a2b8-a4a9-4240-8201-b4f216175376.png)

Products added to the inventory does not have a field showing which user has added it.

**Comment by farhanasafran** [comment]
![image](https://user-images.githubusercontent.com/26750252/169695661-039c317e-c3b1-47c8-b3db-b53f2d62e8cf.png)
![image](https://user-images.githubusercontent.com/26750252/169695670-535bd3c5-3273-4a78-b946-2f72494cb704.png)
users can now see who added what product from the table.

**Comment by farhanasafran** [comment]
CR is completed
