### ISSUE TITLE
Change Request #11 Forgot Password Module

### ISSUE THREAD

**Issue by saniluqman** [saniluqman/G1_Picasso_Inventory_System#11]
Additional user experience for user credentials

**Comment by farhanasafran** [comment]
CCB has decided to reject this Change Request citing the following reasons:
the function is unnecessary as each user only needs to remember their employee ID to access the system. The employee id is theoretically assigned by the shop manager. And as this system is designed for a small shop, there will not be more than 3-4 employee ID in circulation. which the shop manager can keep as a list. Employee is also less likely to forget their employee id.
