### ISSUE TITLE
Change Request #3 Redesign of System Interface

### ISSUE THREAD

**Issue by acutraaq** [saniluqman/G1_Picasso_Inventory_System#3]
This request is to improve UI/UX of the system
 
![image](https://user-images.githubusercontent.com/6891612/169690466-99bec647-8da7-476c-9f62-89146d6643ac.png)

**Comment by trisyialicious** [comment]
AFTER LOGIN PAGE UI:

![image](https://user-images.githubusercontent.com/52111211/169705419-cd9fe1cb-b033-4706-a70e-921de6644107.png)

AFTER GADGET INVENTORY SYSTEM UI:
![image](https://user-images.githubusercontent.com/52111211/169705540-042f0a5a-b893-4cda-9cde-e1ea7d24ec3f.png)

-----------------------------------------------------------------------------
BEFORE SEARCH BAR:

![image](https://user-images.githubusercontent.com/52111211/169705338-ef387a2a-971a-4f7c-8593-07251f3e0714.png)

AFTER SEARCH BAR: 

![image](https://user-images.githubusercontent.com/52111211/169705470-6bc87f1a-e433-41ec-b539-3e8f9a9018f7.png)

-------------------------------------------------------------------------

ADD A NOTIFICATION COLUMN: 

![image](https://user-images.githubusercontent.com/52111211/169705576-c640cd8c-70e8-46a0-b42f-da28598897a0.png)
