### ISSUE TITLE
Change Request #4 Bug: On Screen Inventory Update is Delayed

### ISSUE THREAD

**Issue by acutraaq** [saniluqman/G1_Picasso_Inventory_System#4]
The on screen update of inventory does not immediately follow the database update. This request is  for the improvement of system responsiveness.

**Comment by farhanasafran** [comment]
correction:
![image](https://user-images.githubusercontent.com/26750252/169695359-e2c698d2-6ab9-4211-aa4b-278042587c4b.png)

table now updates following product addition as it should.

**Comment by farhanasafran** [comment]
CR is completed
