### ISSUE TITLE
Change Request #5 Expand of Type(s) of Product to be Recorded in The System

### ISSUE THREAD

**Issue by acutraaq** [saniluqman/G1_Picasso_Inventory_System#5]
This request is to increase the scope of products in the inventory. New database needs to be added for product entry. Currently, the system only allows for insertion of 2 types of product: Laptop and Phone.

![image](https://user-images.githubusercontent.com/6891612/169690727-155ccfdd-8bf7-4135-84f3-aae45cd72b94.png)

**Comment by farhanasafran** [comment]
![image](https://user-images.githubusercontent.com/26750252/169695511-cc5d639a-f651-41fd-9dd3-77e6cb00b3e0.png)
Implemented "Other" object to represent miscellaneous products that can be added to the database

**Comment by farhanasafran** [comment]
CR is completed
