### ISSUE TITLE
Change Request #6 Refinement of Search Function

### ISSUE THREAD

**Issue by acutraaq** [saniluqman/G1_Picasso_Inventory_System#6]
Currently, the search function only works when searching for ID. The improvement of search function, new filters to sort out based on user requirement and finalized with accurate search result needs to be implemented.

![image](https://user-images.githubusercontent.com/6891612/169690923-4624b848-0f19-4114-8ff4-078299404dbc.png)

**Comment by trisyialicious** [comment]
THE SEARCH FUNCTION NOW WORKS WITH BRANDS, MODEL AND COLORS.

LIST OF PHONES:
![image](https://user-images.githubusercontent.com/52111211/169704465-4c8492f8-1eda-4ffb-9fad-2c5bcf0d9e47.png)


SEARCH PHONES BY BRAND:
![image](https://user-images.githubusercontent.com/52111211/169704518-c2498dfc-c5bf-4b72-be92-b71076eceb4e.png)

SEARCH PHONES BY COLOR:
![image](https://user-images.githubusercontent.com/52111211/169704561-ff3f5ad1-3812-4860-8e18-e089c8aa1e4d.png)

SEARCH PHONES BY MODEL:
![image](https://user-images.githubusercontent.com/52111211/169704599-e51555ea-1025-493d-86b2-d37b2512bd56.png)
