### ISSUE TITLE
Change Request #7 Login Function Security Improvement

### ISSUE THREAD

**Issue by saniluqman** [saniluqman/G1_Picasso_Inventory_System#7]
Migrate security issues from hard coded credentials.

**Comment by acutraaq** [comment]
Username and password is hardcoded into the program. This makes the system vulnerable to attacks. Need to be fixed ASAP.
Additional database for storing username and password with encryption needed to increase system security.

![image](https://user-images.githubusercontent.com/6891612/169691732-a71e90e1-84c0-4a29-ac65-13ccf1b04bf5.png)

**Comment by acutraaq** [comment]
Completed. 

![image](https://user-images.githubusercontent.com/6891612/169694501-8c4dbcb0-8a6c-4e3b-9a85-b1c00c463afb.png)

The system will now check the database for a valid employee id which is unique to each employee.

**Comment by farhanasafran** [comment]
CR is completed
