### ISSUE TITLE
Change Request #8 Inventory Notification Module

### ISSUE THREAD

**Issue by saniluqman** [saniluqman/G1_Picasso_Inventory_System#8]
This request is to notify user when the inventory is low. Functional notification should be able to notify user to alert stock is limited.

**Comment by trisyialicious** [comment]
NOTIFICATION MODULE HAVE BEEN SUCCESSFULLY IMPLEMENTED. THE SYSTEM WILL NOTIFY USERS WHENEVER A STOCK REACHES LESS THAN 5 IN THE INVENTORY.


WHEN EVERYTHING IS IN STOCK:
![image](https://user-images.githubusercontent.com/52111211/169704836-61cb1a4c-231f-4176-a8e7-8ddcbf570bf8.png)


WHEN ONE OR MORE PRODUCT HAVE LESS THAN 5:
![image](https://user-images.githubusercontent.com/52111211/169705013-726af010-9d19-418a-8b1a-3320024291db.png)
